development:
  adapter: postgresql
  encoding: unicode
  database: expense_manager_dev
  host: localhost
  pool: 5
  username: root1
  password: toor1

test:
  adapter: postgresql
  encoding: unicode
  database: expense_manager_testdb
  pool: 5
  username: root
  password: toor

production:
  adapter: postgresql
  encoding: unicode
  database: expense_manager_proddb
  pool: 5
  username: root
  password: toor
